using GLMakie
using SPECreader


speceq = SPECEquilibrium("testing/data/G3V01L0Fi.002.sp.h5")

# We can read in the Poincar\'e generated by SPEC during its computation by

poincare = ReadPoincare(speceq)

# If SPEC has not computed an equilibrium we can also generate our own Poincar\'e section'

poincare = construct_poincare(speceq, N_trajs=200, N_orbs=100)

# By default this will compute a Poincar\'e section at ``\\zeta=0``. This returns a `PoincarePlane` object which can be plotted easily,

scatter(poincare.ψ, poincare.θ, markersize=3.0)
